//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_Venta.venta
{

    [Persistent(@"categoria")]
    public partial class Categoria : XPLiteObject
    {
        int fIdcategoria;
        [Key(true)]
        [Persistent(@"idcategoria")]
        public int Idcategoria
        {
            get { return fIdcategoria; }
            set { SetPropertyValue<int>(nameof(Idcategoria), ref fIdcategoria, value); }
        }
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        bool fEstado;
        public bool Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<bool>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"productoReferencescategoria")]
        public XPCollection<Producto> productoes { get { return GetCollection<Producto>(nameof(productoes)); } }
    }

}
