//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_Venta.venta
{

    [Persistent(@"producto")]
    public partial class Producto : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(45)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        DateTime fFecha_Vencimiento;
        public DateTime Fecha_Vencimiento
        {
            get { return fFecha_Vencimiento; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_Vencimiento), ref fFecha_Vencimiento, value); }
        }
        float fPrecio;
        public float Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<float>(nameof(Precio), ref fPrecio, value); }
        }
        int fEstante;
        public int Estante
        {
            get { return fEstante; }
            set { SetPropertyValue<int>(nameof(Estante), ref fEstante, value); }
        }
        Categoria fIdcategoria;
        [Persistent(@"idcategoria")]
        [Association(@"productoReferencescategoria")]
        public Categoria Idcategoria
        {
            get { return fIdcategoria; }
            set { SetPropertyValue<Categoria>(nameof(Idcategoria), ref fIdcategoria, value); }
        }
        bool fEstado;
        public bool Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<bool>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"detalle_ventaReferencesproducto")]
        public XPCollection<Detalle_venta> detalle_ventas { get { return GetCollection<Detalle_venta>(nameof(detalle_ventas)); } }
    }

}
