//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_Venta.venta
{

    [Persistent(@"usuario")]
    public partial class Usuario : XPLiteObject
    {
        int fIdUsuario;
        [Key]
        [Persistent(@"idUsuario")]
        public int IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<int>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        string fUsuario1;
        [Size(45)]
        [Persistent(@"Usuario")]
        public string Usuario1
        {
            get { return fUsuario1; }
            set { SetPropertyValue<string>(nameof(Usuario1), ref fUsuario1, value); }
        }
        string fPassword;
        [Size(45)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        Categoria_usuario fIdcategoria_usuario;
        [Persistent(@"idcategoria_usuario")]
        [Association(@"UsuarioReferencesCategoria_usuario")]
        public Categoria_usuario Idcategoria_usuario
        {
            get { return fIdcategoria_usuario; }
            set { SetPropertyValue<Categoria_usuario>(nameof(Idcategoria_usuario), ref fIdcategoria_usuario, value); }
        }
        bool fEstado;
        [Persistent(@"estado")]
        public bool Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<bool>(nameof(Estado), ref fEstado, value); }
        }
    }

}
